### ISSUE TITLE
[BUG] Incompatible with React 19

### ISSUE THREAD

**Issue by mattgperry** [motiondivision/motion#2668]
Framer Motion is incompatible with React 19.

[Framer](https://framer.com) itself runs on React 18 and given the scope of breaking changes (subtle and major) I think it is unlikely to be upgraded in the near-term.

To support 19, we preferably have to fix types and animations in a way that is backwards compatible with 18. 

Types: https://github.com/framer/motion/issues/2640
Animations: https://github.com/framer/motion/issues/2624

Please add further examples of broken behaviour in the comments here.

**Comment by rubensmit93** [comment]
Interestingly, everything does work after building, but not in dev mode (using Vite)

**Comment by mattgperry** [comment]
Isn't it in dev mode that React now double renders as well as runs double effects?

**Comment by bryanveloso** [comment]
> Isn't it in dev mode that React now double renders as well as runs double effects?

[From the upgrade guide](https://react.dev/blog/2024/04/25/react-19-upgrade-guide), for clarity's sake:

> When double rendering in Strict Mode in development, useMemo and useCallback will reuse the memoized results from the first render during the second render. Components that are already Strict Mode compatible should not notice a difference in behavior.

[...] during development, Strict Mode will double-invoke ref callback functions on initial mount, to simulate what happens when a mounted component is replaced by a Suspense fallback.

**Comment by wouter173** [comment]
I have found that almost all animations break in react 19 with strict mode on. Initial state will be stuck forever and exit animations just instantly snap to the last state. 

Turning off strict mode fixes all of these issues as far as I know. This is, ofcourse, inadvisable.

**Comment by pixel-toys-chris-evans** [comment]
Understand that form the PR this is not a priority and I've been able to work around this issue happily ^ Encountered this during a test upgrade of NextJS which is likely going to _force_ React 19 upon it's users from 14.3.0+ (it currently throws an error at startup and asks you to upgrade to React 19.0.0 >=), so you may see more issues being raised around this particular snafu. 

Just thought I'd throw it out there before the deluge of issues comes in 😂

**Comment by laem** [comment]
Just found this issue after searching for a while why the animations of https://github.com/Temzasse/react-modal-sheet wouldn't work in dev mode, but would in production mode. Very surprising, thanks !

**Comment by mattgperry** [comment]
Track React 19 progress here: https://github.com/framer/motion/pull/2667

Current compatible version is `framer-motion@12.0.0-alpha.0`

**Comment by DrewLandgraveCbsi** [comment]
> Track React 19 progress here: #2667
> 
> Current compatible version is `framer-motion@12.0.0-alpha.0`

Anyone coming here after upgrading to Next 15

It's suggested to use framer-motion@12.0.0-alpha.1 now until react 19 is out

**Comment by anonrose** [comment]
@DrewLandgraveCbsi Yep!

**Comment by alexwindelberg** [comment]
This isn't working for me, I updated to the latest nextJS
![Screenshot 2024-10-24 at 9 00 45 AM](https://github.com/user-attachments/assets/0b289a9f-5d5f-41fb-bc2e-00ccde2541b9)

**Comment by DrewLandgraveCbsi** [comment]
@alexwindelberg Do you have the proper module resolutions/overrides in your package.json?

I'm using yarn so it looks like
```
  "resolutions": {
    "@types/react": "npm:types-react@19.0.0-rc.1",
    "@types/react-dom": "npm:types-react-dom@19.0.0-rc.1"
  }
```

For npm I think it's
```
  "overrides": {
    "@types/react": "npm:types-react@19.0.0-rc.1",
    "@types/react-dom": "npm:types-react-dom@19.0.0-rc.1"
  }
```

**Comment by alexwindelberg** [comment]
@DrewLandgraveCbsi , thank you this helped

**Comment by oncet** [comment]
Trying to install v12 I still get same error:

```
npm install framer-motion@v12.0.0-alpha.1
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: framer-motion@12.0.0-alpha.1
npm error Found: react@19.0.0-rc-02c0e824-20241028
npm error node_modules/react
npm error   peer react@"^18.2.0 || 19.0.0-rc-02c0e824-20241028" from next@15.0.2
npm error   node_modules/next
npm error     next@"15.0.2" from the root project
npm error   peer react@"19.0.0-rc-02c0e824-20241028" from react-dom@19.0.0-rc-02c0e824-20241028
npm error   node_modules/react-dom
npm error     peer react-dom@"^18.2.0 || 19.0.0-rc-02c0e824-20241028" from next@15.0.2
npm error     node_modules/next
npm error       next@"15.0.2" from the root project
npm error     react-dom@"19.0.0-rc-02c0e824-20241028" from the root project
npm error   2 more (styled-jsx, the root project)
npm error
npm error Could not resolve dependency:
npm error peerOptional react@"^18.0.0" from framer-motion@12.0.0-alpha.1
npm error node_modules/framer-motion
npm error   framer-motion@"v12.0.0-alpha.1" from the root project
npm error
npm error Conflicting peer dependency: react@18.3.1
npm error node_modules/react
npm error   peerOptional react@"^18.0.0" from framer-motion@12.0.0-alpha.1
npm error   node_modules/framer-motion
npm error     framer-motion@"v12.0.0-alpha.1" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /Users/foo/.npm/_logs/2024-10-31T19_59_55_100Z-eresolve-report.txt
npm error A complete log of this run can be found in: /Users/foo/.npm/_logs/2024-10-31T19_59_55_100Z-debug-0.log
```

**Comment by mergd** [comment]
Upgrading to `^12.0.0-alpha.1`	fixed issue with the LSP not recognizing the `className` prop

**Comment by ishan0102** [comment]
Still seeing a bug where the initial opacity always remains and never transitions, but only during development. Using `12.0.0-alpha.1`. Flipping `reactStrictMode` to `false` fixes it for me so I suspect there's something weird there.

**Comment by david-randoll** [comment]
I did `npm install framer-motion@v12.0.0-alpha.1 --force` and was about to install it

**Comment by david-randoll** [comment]
> Trying to install `v12`:
> 
> ```
> npm install framer-motion@v12.0.0-alpha.1
> npm error code ERESOLVE
> npm error ERESOLVE could not resolve
> npm error
> npm error While resolving: framer-motion@12.0.0-alpha.1
> npm error Found: react@19.0.0-rc-02c0e824-20241028
> npm error node_modules/react
> npm error   peer react@"^18.2.0 || 19.0.0-rc-02c0e824-20241028" from next@15.0.2
> npm error   node_modules/next
> npm error     next@"15.0.2" from the root project
> npm error   peer react@"19.0.0-rc-02c0e824-20241028" from react-dom@19.0.0-rc-02c0e824-20241028
> npm error   node_modules/react-dom
> npm error     peer react-dom@"^18.2.0 || 19.0.0-rc-02c0e824-20241028" from next@15.0.2
> npm error     node_modules/next
> npm error       next@"15.0.2" from the root project
> npm error     react-dom@"19.0.0-rc-02c0e824-20241028" from the root project
> npm error   2 more (styled-jsx, the root project)
> npm error
> npm error Could not resolve dependency:
> npm error peerOptional react@"^18.0.0" from framer-motion@12.0.0-alpha.1
> npm error node_modules/framer-motion
> npm error   framer-motion@"v12.0.0-alpha.1" from the root project
> npm error
> npm error Conflicting peer dependency: react@18.3.1
> npm error node_modules/react
> npm error   peerOptional react@"^18.0.0" from framer-motion@12.0.0-alpha.1
> npm error   node_modules/framer-motion
> npm error     framer-motion@"v12.0.0-alpha.1" from the root project
> ```
> 
> Also tried with `override` option but I get same error:
> 
> ```
> {
>   "dependencies": {
>     "@types/react": "npm:types-react@rc",
>     "@types/react-dom": "npm:types-react-dom@rc"
>   },
>   "overrides": {
>     "@types/react": "npm:types-react@rc",
>     "@types/react-dom": "npm:types-react-dom@rc"
>   }
> }
> ```
> 
> Looking at the source code, seems to still be requiring React v18:
> 
> * https://github.com/framer/motion/blob/v12.0.0-alpha.1/packages/framer-motion/package.json#L84-L85
> 
> What I'm missing?

I did npm install framer-motion@v12.0.0-alpha.1 --force and was able to install it

**Comment by oncet** [comment]
> > Trying to install `v12`:
> > ```
> > npm install framer-motion@v12.0.0-alpha.1
> > npm error code ERESOLVE
> > npm error ERESOLVE could not resolve
> > npm error
> > npm error While resolving: framer-motion@12.0.0-alpha.1
> > npm error Found: react@19.0.0-rc-02c0e824-20241028
> > npm error node_modules/react
> > npm error   peer react@"^18.2.0 || 19.0.0-rc-02c0e824-20241028" from next@15.0.2
> > npm error   node_modules/next
> > npm error     next@"15.0.2" from the root project
> > npm error   peer react@"19.0.0-rc-02c0e824-20241028" from react-dom@19.0.0-rc-02c0e824-20241028
> > npm error   node_modules/react-dom
> > npm error     peer react-dom@"^18.2.0 || 19.0.0-rc-02c0e824-20241028" from next@15.0.2
> > npm error     node_modules/next
> > npm error       next@"15.0.2" from the root project
> > npm error     react-dom@"19.0.0-rc-02c0e824-20241028" from the root project
> > npm error   2 more (styled-jsx, the root project)
> > npm error
> > npm error Could not resolve dependency:
> > npm error peerOptional react@"^18.0.0" from framer-motion@12.0.0-alpha.1
> > npm error node_modules/framer-motion
> > npm error   framer-motion@"v12.0.0-alpha.1" from the root project
> > npm error
> > npm error Conflicting peer dependency: react@18.3.1
> > npm error node_modules/react
> > npm error   peerOptional react@"^18.0.0" from framer-motion@12.0.0-alpha.1
> > npm error   node_modules/framer-motion
> > npm error     framer-motion@"v12.0.0-alpha.1" from the root project
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also tried with `override` option but I get same error:
> > ```
> > {
> >   "dependencies": {
> >     "@types/react": "npm:types-react@rc",
> >     "@types/react-dom": "npm:types-react-dom@rc"
> >   },
> >   "overrides": {
> >     "@types/react": "npm:types-react@rc",
> >     "@types/react-dom": "npm:types-react-dom@rc"
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Looking at the source code, seems to still be requiring React v18:
> > 
> > * https://github.com/framer/motion/blob/v12.0.0-alpha.1/packages/framer-motion/package.json#L84-L85
> > 
> > What I'm missing?
> 
> I did npm install framer-motion@v12.0.0-alpha.1 --force and was able to install it

I don't think it should be necessary to do force install.

**Comment by longzheng** [comment]
I got `overrides` to work with

```json
    "dependencies": {
        "framer-motion": "^12.0.0-alpha.1",
        "next": "15.0.3",
        "react": "19.0.0-rc-66855b96-20241106",
        "react-dom": "19.0.0-rc-66855b96-20241106"
    },
    "overrides": {
        "framer-motion": {
            "react": "19.0.0-rc-66855b96-20241106",
            "react-dom": "19.0.0-rc-66855b96-20241106"
        }
    }
```

**Comment by ArishN** [comment]
i am using next js 15 and i try to install framer motion on it but it throw error like

 npm i framer-motion
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: framer-motion@11.11.17
npm error Found: react@19.0.0-rc-b01722d5-20241114
npm error node_modules/react
npm error   peer react@"19.0.0-rc-b01722d5-20241114" from react-dom@19.0.0-rc-b01722d5-20241114
npm error   node_modules/react-dom
npm error     react-dom@"19.0.0-rc-b01722d5-20241114" from the root project
npm error   peer react@"*" from react-icons@5.3.0
npm error   node_modules/react-icons
npm error     react-icons@"^5.3.0" from the root project
npm error   2 more (styled-jsx, the root project)
npm error
npm error Could not resolve dependency:
npm error peerOptional react@"^18.0.0" from framer-motion@11.11.17
npm error node_modules/framer-motion
npm error   framer-motion@"*" from the root project
npm error
npm error Conflicting peer dependency: react@18.3.1
npm error node_modules/react
npm error   peerOptional react@"^18.0.0" from framer-motion@11.11.17
npm error   node_modules/framer-motion
npm error     framer-motion@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error C:\Users\Admin\AppData\Local\npm-cache\_logs\2024-11-15T07_42_16_461Z-eresolve-report.txt
npm error A complete log of this run can be found in: C:\Users\Admin\AppData\Local\npm-cache\_logs\2024-11-15T07_42_16_461Z-debug-0.log



when i try to downgrade my react version to 18 it works i mean it got installed is that advisable to downgrade that? 

here is my dependencies in package manager :

{

  "dependencies": {
    "mini-svg-data-uri": "^1.4.4",
    "next": "15.0.3",
    "react": "19.0.0-rc-b01722d5-20241114",
    "react-dom": "19.0.0-rc-b01722d5-20241114",
    "react-icons": "^5.3.0"
  },
}

**Comment by andr3wV** [comment]
> I got `overrides` to work with
> 
> ```json
>     "dependencies": {
>         "framer-motion": "^12.0.0-alpha.1",
>         "next": "15.0.3",
>         "react": "19.0.0-rc-66855b96-20241106",
>         "react-dom": "19.0.0-rc-66855b96-20241106"
>     },
>     "overrides": {
>         "framer-motion": {
>             "react": "19.0.0-rc-66855b96-20241106",
>             "react-dom": "19.0.0-rc-66855b96-20241106"
>         }
>     }
> ```
> 
> Then `npm install` will work without needing `--force`

This is the only solution works for me when upgrading to Next15. Thanks!

**Comment by oncet** [comment]
> I got `overrides` to work with
> 
> ```json
>     "dependencies": {
>         "framer-motion": "^12.0.0-alpha.1",
>         "next": "15.0.3",
>         "react": "19.0.0-rc-66855b96-20241106",
>         "react-dom": "19.0.0-rc-66855b96-20241106"
>     },
>     "overrides": {
>         "framer-motion": {
>             "react": "19.0.0-rc-66855b96-20241106",
>             "react-dom": "19.0.0-rc-66855b96-20241106"
>         }
>     }
> ```
> 
> Then `npm install` will work without needing `--force`

Yes, this works. But isn't `framer-motion@12.0.0-alpha.1` supposed to be using React 19 already?

**Comment by mohit-hexa** [comment]
I m still getting the error 

hexa@hexas-MacBook-Air hexa-carbon-web-fe % npm install framer-motion@v12.0.0-alpha.1

(node:63392) ExperimentalWarning: CommonJS module /opt/homebrew/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /opt/homebrew/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: framer-motion@12.0.0-alpha.1
npm error Found: react@19.0.0-rc-66855b96-20241106
npm error node_modules/react
npm error   peer react@"^16.8 || ^17.0 || ^18.0 || ^19.0 || ^19.0.0-rc" from @radix-ui/react-compose-refs@1.1.0
npm error   node_modules/@radix-ui/react-compose-refs
npm error     @radix-ui/react-compose-refs@"1.1.0" from @radix-ui/react-slot@1.1.0
npm error     node_modules/@radix-ui/react-slot
npm error       @radix-ui/react-slot@"^1.1.0" from the root project
npm error   peer react@"^16.8 || ^17.0 || ^18.0 || ^19.0 || ^19.0.0-rc" from @radix-ui/react-slot@1.1.0
npm error   node_modules/@radix-ui/react-slot
npm error     @radix-ui/react-slot@"^1.1.0" from the root project
npm error   5 more (lucide-react, next, react-dom, styled-jsx, the root project)
npm error
npm error Could not resolve dependency:
npm error peerOptional react@"^18.0.0" from framer-motion@12.0.0-alpha.1
npm error node_modules/framer-motion
npm error   framer-motion@"v12.0.0-alpha.1" from the root project
npm error
npm error Conflicting peer dependency: react@18.3.1
npm error node_modules/react
npm error   peerOptional react@"^18.0.0" from framer-motion@12.0.0-alpha.1
npm error   node_modules/framer-motion
npm error     framer-motion@"v12.0.0-alpha.1" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /Users/hexa/.npm/_logs/2024-11-18T14_01_02_371Z-eresolve-report.txt
npm error A complete log of this run can be found in: /Users/hexa/.npm/_logs/2024-11-18T14_01_02_371Z-debug-0.log
hexa@hexas-MacBook-Air hexa-carbon-web-fe % npm install framer-motion@v12.0.0-alpha.1

**Comment by longzheng** [comment]
> > I got `overrides` to work with
> > ```json
> >     "dependencies": {
> >         "framer-motion": "^12.0.0-alpha.1",
> >         "next": "15.0.3",
> >         "react": "19.0.0-rc-66855b96-20241106",
> >         "react-dom": "19.0.0-rc-66855b96-20241106"
> >     },
> >     "overrides": {
> >         "framer-motion": {
> >             "react": "19.0.0-rc-66855b96-20241106",
> >             "react-dom": "19.0.0-rc-66855b96-20241106"
> >         }
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then `npm install` will work without needing `--force`
> 
> Yes, this works. But isn't `framer-motion@12.0.0-alpha.1` supposed to be using React 19 already?

It's compatible with React 19 but the `peerDependencies` still reference React 18

https://github.com/motiondivision/motion/blob/4aa88d2d1e5ff9a94e826b0b05dbd625e5ec37df/packages/framer-motion/package.json#L82-L86

**Comment by jerrywonderr** [comment]
> I got `overrides` to work with
> 
> ```json
>     "dependencies": {
>         "framer-motion": "^12.0.0-alpha.1",
>         "next": "15.0.3",
>         "react": "19.0.0-rc-66855b96-20241106",
>         "react-dom": "19.0.0-rc-66855b96-20241106"
>     },
>     "overrides": {
>         "framer-motion": {
>             "react": "19.0.0-rc-66855b96-20241106",
>             "react-dom": "19.0.0-rc-66855b96-20241106"
>         }
>     }
> ```
> 
> Then `npm install` will work without needing `--force`

This worked for me. Thank you

**Comment by FathZulfaAli** [comment]
> I got `overrides` to work with
> 
> ```json
>     "dependencies": {
>         "framer-motion": "^12.0.0-alpha.1",
>         "next": "15.0.3",
>         "react": "19.0.0-rc-66855b96-20241106",
>         "react-dom": "19.0.0-rc-66855b96-20241106"
>     },
>     "overrides": {
>         "framer-motion": {
>             "react": "19.0.0-rc-66855b96-20241106",
>             "react-dom": "19.0.0-rc-66855b96-20241106"
>         }
>     }
> ```
> 
> Then `npm install` will work without needing `--force`

For my case its work for installing but soon I use motion.div from "framer-motion" it got error

![image](https://github.com/user-attachments/assets/91dc7843-56ed-4c25-b17c-110d97e703bd)

for reference my package.json
```json
"dependencies": {
    "framer-motion": "^12.0.0-alpha.1",
    "next": "15.0.3",
    "react": "19.0.0-rc-66855b96-20241106",
    "react-dom": "19.0.0-rc-66855b96-20241106"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "eslint": "^8",
    "eslint-config-next": "15.0.3",
    "postcss": "^8",
    "tailwindcss": "^3.4.1",
    "typescript": "^5"
  },
  "overrides": {
    "framer-motion": {
      "react": "19.0.0-rc-66855b96-20241106",
      "react-dom": "19.0.0-rc-66855b96-20241106"
     }
   }
```

**Comment by mattgperry** [comment]
FYI `motion@12.0.0-alpha.2` is out now, let me know if this fixes the need for overrides.

**Comment by FathZulfaAli** [comment]
> > I got `overrides` to work with
> > ```json
> >     "dependencies": {
> >         "framer-motion": "^12.0.0-alpha.1",
> >         "next": "15.0.3",
> >         "react": "19.0.0-rc-66855b96-20241106",
> >         "react-dom": "19.0.0-rc-66855b96-20241106"
> >     },
> >     "overrides": {
> >         "framer-motion": {
> >             "react": "19.0.0-rc-66855b96-20241106",
> >             "react-dom": "19.0.0-rc-66855b96-20241106"
> >         }
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then `npm install` will work without needing `--force`
> 
> For my case its work for installing but soon I use motion.div from "framer-motion" it got error
> 
> ![image](https://private-user-images.githubusercontent.com/89955215/389470749-91dc7843-56ed-4c25-b17c-110d97e703bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MjkwNTcsIm5iZiI6MTczMjUyODc1NywicGF0aCI6Ii84OTk1NTIxNS8zODk0NzA3NDktOTFkYzc4NDMtNTZlZC00YzI1LWIxN2MtMTEwZDk3ZTcwM2JkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDA5NTkxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyZGQyMDFlYWY3YTA4Mjc1NmVmNzdjYzZmMGM4MWM5NTU4YTg3ZDA1ZTQ4MmVmMDBlOGJiY2NhZTI5ZWFhZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gUcen8dvQJDVo-ZaFnAMsXITlRJ_MIOi9RT3MZNKHBY)
> 
> for reference my package.json
> 
> ```json
> "dependencies": {
>     "framer-motion": "^12.0.0-alpha.1",
>     "next": "15.0.3",
>     "react": "19.0.0-rc-66855b96-20241106",
>     "react-dom": "19.0.0-rc-66855b96-20241106"
>   },
>   "devDependencies": {
>     "@types/node": "^20",
>     "@types/react": "^18",
>     "@types/react-dom": "^18",
>     "eslint": "^8",
>     "eslint-config-next": "15.0.3",
>     "postcss": "^8",
>     "tailwindcss": "^3.4.1",
>     "typescript": "^5"
>   },
>   "overrides": {
>     "framer-motion": {
>       "react": "19.0.0-rc-66855b96-20241106",
>       "react-dom": "19.0.0-rc-66855b96-20241106"
>      }
>    }
> ```

My bad I've learned the "use client" is needed at the top of the file

**Comment by joevingracien** [comment]
> > > I got `overrides` to work with
> > > ```json
> > >     "dependencies": {
> > >         "framer-motion": "^12.0.0-alpha.1",
> > >         "next": "15.0.3",
> > >         "react": "19.0.0-rc-66855b96-20241106",
> > >         "react-dom": "19.0.0-rc-66855b96-20241106"
> > >     },
> > >     "overrides": {
> > >         "framer-motion": {
> > >             "react": "19.0.0-rc-66855b96-20241106",
> > >             "react-dom": "19.0.0-rc-66855b96-20241106"
> > >         }
> > >     }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Then `npm install` will work without needing `--force`
> > 
> > 
> > For my case its work for installing but soon I use motion.div from "framer-motion" it got error
> > ![image](https://private-user-images.githubusercontent.com/89955215/389470749-91dc7843-56ed-4c25-b17c-110d97e703bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MjkwNTcsIm5iZiI6MTczMjUyODc1NywicGF0aCI6Ii84OTk1NTIxNS8zODk0NzA3NDktOTFkYzc4NDMtNTZlZC00YzI1LWIxN2MtMTEwZDk3ZTcwM2JkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDA5NTkxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyZGQyMDFlYWY3YTA4Mjc1NmVmNzdjYzZmMGM4MWM5NTU4YTg3ZDA1ZTQ4MmVmMDBlOGJiY2NhZTI5ZWFhZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gUcen8dvQJDVo-ZaFnAMsXITlRJ_MIOi9RT3MZNKHBY)
> > for reference my package.json
> > ```json
> > "dependencies": {
> >     "framer-motion": "^12.0.0-alpha.1",
> >     "next": "15.0.3",
> >     "react": "19.0.0-rc-66855b96-20241106",
> >     "react-dom": "19.0.0-rc-66855b96-20241106"
> >   },
> >   "devDependencies": {
> >     "@types/node": "^20",
> >     "@types/react": "^18",
> >     "@types/react-dom": "^18",
> >     "eslint": "^8",
> >     "eslint-config-next": "15.0.3",
> >     "postcss": "^8",
> >     "tailwindcss": "^3.4.1",
> >     "typescript": "^5"
> >   },
> >   "overrides": {
> >     "framer-motion": {
> >       "react": "19.0.0-rc-66855b96-20241106",
> >       "react-dom": "19.0.0-rc-66855b96-20241106"
> >      }
> >    }
> > ```
> 
> My bad I've learned the "use client" is needed at the top of the file, it work thanks

Never tested it but, to my understanding, it appears we don't need "use client" if we use:
// React Server Components
import * as motion from "motion/client"

https://motion.dev/docs/react-motion-component#usage

**Comment by ArishN** [comment]
> > FYI `motion@12.0.0-alpha.2` is out now, let me know if this fixes the need for overrides.
> 
>  I did when I deployed on Vercel because it was using “npm install” during the build for installing dependencies, so I had to override it with “npm install —legacy-peer-deps“ and it worked

If I am not wrong , after using “npm install —legacy-peer-deps“ you cannot install any other libraries or packages. If you try to install it will throw error.

**Comment by markomitranic** [comment]
I'm using react 19 due to Next 15 in a Turborepo.
Instead of doing manual overrides for each package, I've followed this advice https://github.com/vercel/next.js/issues/72899#issuecomment-2501695993 and everything except framer worked fine (althought I've had to use `npm i --force`).

Framer components started tossing various TS warnings due to missing types. Then I applied the 12 alpha as suggested by @ArishN above and it seems to work fine. All  the TS errors are gone, and my animations still work fine so far.

**Comment by spaciousejar** [comment]
![Screenshot_2024-12-09-18-31-33_1366x768](https://github.com/user-attachments/assets/54ed4449-6899-4d3b-98ea-b4fec711f4b3)

**Comment by 6abotage** [comment]
> FYI `motion@12.0.0-alpha.2` is out now, let me know if this fixes the need for overrides.

I tested it and it works great

`   
"framer-motion": "^12.0.0-alpha.2",
"react": "^19.0.0",
"react-dom": "^19.0.0",
`

**Comment by mattgperry** [comment]
@6abotage  You can try `11.13.4` too now!

**Comment by dgtllion** [comment]
i still get warning when install 11.13.4 with pnpm
```
 WARN  Issues with peer dependencies found
.
└─┬ framer-motion 11.13.4
  ├── ✕ unmet peer react@^18.0.0: found 19.0.0
  └── ✕ unmet peer react-dom@^18.0.0: found 19.0.0

```

**Comment by mattgperry** [comment]
11.13.5 should have fixed this

**Comment by dgtllion** [comment]
yeah now it works, Thanks a lot!

**Comment by boar-is** [comment]
![image](https://github.com/user-attachments/assets/11ac7e81-89e7-4f1c-bf96-b7bde0fe7acd)

**Comment by mattgperry** [comment]
Ah good catch, working on that now thanks

**Comment by 6abotage** [comment]
> Ah good catch, working on that now thanks

Works great, thank you for your fast work!

**Comment by robreiss** [comment]
Just a quick tip/data point:

I'm using Framer Motion 12.0.0-alpha.2 with React 19 and Next.js 15, with the React compiler enabled (probably not recommended). Overall, things are working well for me.

Initially, I ran into an issue where some animations weren't functioning as expected. However, I was able to resolve it by using the "use no memo" directive to opt out of the React compiler for a component utilizing Framer Motion. After doing that, the animations started working properly.

Hope this helps someone encountering similar issues.

**Comment by igorkoho** [comment]
@mattgperry not sure if I've missed something, but if we want the vanilla-js version of the package, we still need to just install the "motion" package, right? I am getting the react peer deps issue as well, but react is not really part of my app -- it's just in the project for storybook.

**Comment by mattgperry** [comment]
@igorkoho what’s the exact error? I wonder if Storybook has an older version of React, as those deps are marked as optional so it should only fail if they’re present but don’t meet 18

**Comment by igorkoho** [comment]
This was the exact error. TBH I'm not even sure if I need react installed as an explicit dependency. Removing it _seems_ to work for storybook, but I suppose I may run into some edge case where there is an issue.

```
# npm resolution error report

While resolving: motion@11.14.1
Found: react@16.14.0
node_modules/react
  peerOptional react@"^18.0.0 || ^19.0.0" from framer-motion@11.14.1
  node_modules/motion/node_modules/framer-motion
    framer-motion@"^11.14.1" from motion@11.14.1
    node_modules/motion
      motion@"*" from the root project

Could not resolve dependency:
peerOptional react@"^18.0.0 || ^19.0.0" from motion@11.14.1
node_modules/motion
  motion@"*" from the root project

Conflicting peer dependency: react@19.0.0
node_modules/react
  peerOptional react@"^18.0.0 || ^19.0.0" from motion@11.14.1
  node_modules/motion
    motion@"*" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by igorkoho** [comment]
For the record, I resolved this in my project by just upgrading my storybook to v8, which doesn't require me to have react installed. Still, if there were an option to install a vanilla version of this plugin without the react peer-dep, IMO that would be great.

**Comment by mattgperry** [comment]
The peer dep is optional so now that Storybook doesn’t require it - it won’t be installed. It was the version mismatch that was the problem.

**Comment by igorkoho** [comment]
I understand, but the version of react I had installed for storybook IMO should be irrelevant for my usage of motion, which I was planning on using in vanilla JS mode. Totally understandable if keeping these packages in one install is what is needed to make shipping both more manageable, I suppose it not working in my case is an edge case.

**Comment by levisstrauss** [comment]
Animation is a browser interaction that is why we need to add "use client" before <motion.div> can start working and don't forget to import it at the top: import {motion} from "framer-motion";

**Comment by igorlopasovsky** [comment]
@mattgperry Sorry for coming back to this issue but has it been resolved? I use `React 19.1.0` together with `Motion 12.9.4` and `layout` animations don't work in `Vite` dev mode. They however do work in production after running `npm run build`. 

They also work when I downgrade `React` to `18.3.0` with the latest `Motion` version or keep `React` at `19.1.0` and downgrade `Motion` to `11.18.2`.

**Comment by tandebnath** [comment]
@igorlopasovsky Did you get any updates on your last comment?

**Comment by igorlopasovsky** [comment]
@tandebnath No, I didn't. Right now I ended up with `React 19.1.0` and `Motion 11.18.2`.
