### ISSUE TITLE
[BUG] `motion/mini` doesn't exist but there's an `animateMini` in `motion`

### ISSUE THREAD

**Issue by brandonpittman** [motiondivision/motion#2865]
Docs say to use `import {animate} from "motion/mini"` but it doesn't exist.

`import {animateMini} from "motion"` does.

**Comment by mattgperry** [comment]
Can you check `11.11.15` to see if this fixes it for you?

**Comment by litingyes** [comment]
> Can you check `11.11.15` to see if this fixes it for you?

cann't find the type file

<img width="815" alt="Screenshot 2024-11-13 at 22 45 51" src="https://github.com/user-attachments/assets/4610b787-a98c-496f-9e93-0102073ca1fd">
<img width="846" alt="Screenshot 2024-11-13 at 22 46 12" src="https://github.com/user-attachments/assets/07d9315f-9b21-41d2-bd2e-efe37845251b">

**Comment by pleskac** [comment]
The type file isn't found as mentioned above on `11.11.15` and the types are actually incorrect. I don't believe `x`/`y`/`z` are valid keyframes anymore after moving away from the css var implementation? They don't work in practice but I believe the types are just shared with `framer-motion`.

**Comment by brandonpittman** [comment]
Working as expected!
