### ISSUE TITLE
Docs: Incorrect path for bundle size

### ISSUE THREAD

**Issue by johnchourajr** [motiondivision/motion#2871]
When I click on https://motion.dev/docs/react-reduce-bundlesize on the [Lazy Motion](https://motion.dev/docs/react-lazy-motion) page, it goes to a 404. 

I'd expect it to go to: https://motion.dev/docs/react-reduce-bundle-size

Just looks like a url typo of `react-reduce-bundlesize` which should be `react-reduce-bundle-size`

😄

**Comment by mattgperry** [comment]
Fixed, thanks for the report!
