### ISSUE TITLE
[BUG] Layout + border radius + border width doesn't animate correctly

### ISSUE THREAD

**Issue by kelseyyoung** [motiondivision/motion#2911]
**1. Read the [FAQs](#faqs) 👇** 

Done!

**2. Describe the bug**

I'm trying to use the `layout` prop because I want to get the benefits of being able to animate things that aren't animatable in CSS, as described [here](https://motion.dev/docs/react-layout-animations). However I'm having issues when using the prop alongside animating things like width, height, position, border-radius, and border-width

This issue is 50% "I think there is a bug" and 50% "maybe I'm doing this incorrectly" 😅 

1. Using layout={true} distorts the border undesirably at the beginning of the animation, although at the end of the animation it looks similar to its CSS-only counterpart
2. Using layout={"position"} to try and get rid of that distortion (from the width & height transform) makes the animation look good at the start, but the ending border radius is incorrect and it "snaps" at the end of the transition

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

[Link to the CodeSandbox](https://codesandbox.io/p/sandbox/nervous-joliot-w7sjf3). Note the Motion version used is older to replicate my environment, although I made another sandbox on latest and it still repro-d

**4. Steps to reproduce**

Click on the "Trigger animations" button in the top right.
1. The top rectangle has a wide/stretched border at the beginning of the animation but ends up looking like the CSS-only version towards the end
2. The middle rectangle starts its animation looking similar to the CSS-only version, but the border radius is incorrect at the end
3. The bottom rectangle is CSS-only, note how everything smoothly transitions

**5. Expected behavior**

I would like to find a way to get the animation effect of the bottom rectangle, which is using raw CSS transitions

**6. Video or screenshots**

https://github.com/user-attachments/assets/d9540004-0224-429b-a79b-846975cfe826

**7. Environment details**

Not sure if applicable, running on Mac and latest Chrome

**Comment by mattgperry** [comment]
Thanks for the questions and apologises for the confusion. This wasn't mentioned in the docs, but I've just added a section addressing this:

https://motion.dev/docs/react-layout-animations#border-looks-stretched-during-animation
