### ISSUE TITLE
[FEATURE] ensure vanilla examples don't include react code

### ISSUE THREAD

**Issue by danielo515** [motiondivision/motion#2919]
Many vanilla examples include what looks like react code `motion.div`, etc. Will be nice if instead proper vanilla examples were provided

**Comment by danielo515** [comment]
Yes, sure. Sorry I opened it from my phone.
In the animate, starting from tween it includes a bunch of `motion.div` entries

https://motion.dev/docs/animate#tween

**Comment by danielo515** [comment]
was the provided information enough?

**Comment by mattgperry** [comment]
Oh yeah perfect thanks for the detail!

**Comment by mattgperry** [comment]
Okay those references have been replaced now, thanks for the heads up!
