### ISSUE TITLE
[FEATURE] type support of react 19 ref as props

### ISSUE THREAD

**Issue by codehz** [motiondivision/motion#2925]
**Is your feature request related to a problem? Please describe.**
react 19 support ref as props, but motion.create only allow ForwardRefExoticComponent as input

**Describe the solution you'd like**
modify the type of motion.create accept normal function component

**Describe alternatives you've considered**
create a wrapper to cast type

**Additional context**
current workaround
```ts
function createMotion<T>(
  render: FunctionComponent<T>
): ExoticComponent<MotionComponentProps<T>> {
  return motion.create(render as any);
}
```
I tested, it works in runtime

**Comment by faradaytrs** [comment]
Same issue here, i use alpha channel and it still expects to forwardRef
