### ISSUE TITLE
[BUG]  motion.div Type Definitions Missing HTML Div Properties in React 19

### ISSUE THREAD

**Issue by faradaytrs** [motiondivision/motion#2926]
# Bug Report: motion.div Type Definitions Missing HTML Div Properties in React 19

## Description
The `motion.div` component from Framer Motion appears to be missing TypeScript definitions for standard HTML div properties like `onClick` and `className` when used with React 19. This affects all HTML div properties that should normally be available through the HTMLDivElement interface.

## Current Behavior
TypeScript shows type errors for common div properties on `motion.div`:
- `onClick` event handler not recognized
- `className` property not recognized
- Other standard HTML div properties likely affected

<img width="864" alt="Screenshot 2024-12-06 at 14 52 16" src="https://github.com/user-attachments/assets/c5603e9a-6f0b-44c5-abfb-722faf6deed4">

## Expected Behavior
`motion.div` should inherit all standard HTML div properties as it's an enhanced version of a regular div element.

## Code Example

````tsx
<motion.div
    onClick={(e) => { // TypeScript error: Property 'onClick' does not exist
        e.stopPropagation();
        if (status === "inactive") {
            return onClickNext?.();
        }
    }}
    className={cn( // TypeScript error: Property 'className' does not exist
        "ds:text-[16.26px] dm:text-[17.92px] dl:text-[19.1px] absolute right-[13.33em]",
         className,
    )}
    // ... other properties
>
````

## Environment
- React: 19.0.0 with types 19.0.0
- Motion: 11.13.1
- TypeScript: 5.7.2

## Possible Solutions
1. Update Framer Motion types to explicitly include HTMLDivElement properties

**Comment by larixk** [comment]
Ran into this as well, but think this issue might be a duplicate of https://github.com/motiondivision/motion/issues/2843

**Comment by faradaytrs** [comment]
> Ran into this as well, but think this issue might be a duplicate of #2843

i think so, i will try alpha version instead
