### ISSUE TITLE
[BUG] Colors don't animate

### ISSUE THREAD

**Issue by darrencoen** [motiondivision/motion#2927]
backgroundColor and color do not animate. I would venture to guess that border colors as well.

https://codesandbox.io/p/sandbox/first-animation-forked-3h5jvl?file=%2Fscript.js%3A12%2C1

This is something that did work in motion 10.x before it merged with framer motion. perhaps there is a new paradigm?

```import { animate } from "https://cdn.jsdelivr.net/npm/motion@11.11.13/+esm";

animate(
  "h1",
  {
    color: ["white", "black"],
    backgroundColor: ["red", "blue"],
    fontSize: ["2em", "3em"],
  },
  { duration: 3 }
);
```
Above code, only font size animates, the text is black, the box is blue.

**Comment by mattgperry** [comment]
Hey @darrencoen 

This will work if you use `import { animate } from "motion/mini"`, reason being this is the lightweight WAAPI-only import that more closely mirrors `animate` from Motion One.

It could be possible to support this in the future though one of the reasons the hybrid animation function has such good performance is to interrupt WAAPI animations it spins up a JS animation and samples that at `currentTime`. Which means it can only support values that the JS animation engine supports.
