### ISSUE TITLE
[BUG] TypeError when use `className`

### ISSUE THREAD

**Issue by Redish101** [motiondivision/motion#2929]
When I add the className property to a Framer Motion component, an error occurs: "Property 'className' does not exist on type 'IntrinsicAttributes & HTMLAttributesWithoutMotionProps<unknown, unknown> & MotionProps & RefAttributes<HTMLHeadingElement>'."

```tsx
<motion.h1
          className="text-4xl font-medium"
          animate={{ y: 0, opacity: 1 }}
          initial={{ y: -10, opacity: 0 }}
          transition={{ duration: 0.4 }}
        >
          {site?.name}
        </motion.h1>
```
Below are my framer-motion, React and React-DOM versions.
```json
"dependencies": {
    "framer-motion": "^11.13.1",
    "react": "^19.0.0",
    "react-dom": "^19.0.0"
  },
```

**Comment by mattgperry** [comment]
Can you do me a favour and try 11.13.3 too?

**Comment by bbortt** [comment]
> Can you do me a favour and try 11.13.3 too?

@mattgperry I've tried `11.13.4` and that works.
