### ISSUE TITLE
[BUG] Release 11.13.2 and 11.13.3?

### ISSUE THREAD

**Issue by billyjanitsch** [motiondivision/motion#2931]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

There are git tags and changelog entries for versions 11.13.2 and 11.13.3, but neither version has been [published to npm](https://www.npmjs.com/package/framer-motion?activeTab=versions).

Maybe this was an oversight or an issue caused by the recent repository migration? Just raising in case you were unaware. Thanks!

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

n/a

**4. Steps to reproduce**

```
npm install framer-motion@11.13.3
```

**5. Expected behavior**

The package should install.

**6. Video or screenshots**

n/a

**7. Environment details**

n/a

**Comment by mattgperry** [comment]
Yeah I’ve had some problems publishing “framer-motion” to npm over the weekend since leaving the framer organisation, we just transferred it over to my account so 11.13.3 will go out tomorrow morning!

**Comment by mattgperry** [comment]
It’s out!
