### ISSUE TITLE
[BUG] Not enough sponsors

### ISSUE THREAD

**Issue by volkyeth** [motiondivision/motion#2933]
I'm sorry for adding this one to your backlog, but it must be tracked

How TF do you only have 3 sponsors?

C'mon people...pitch in: https://github.com/sponsors/mattgperry

**Comment by mattgperry** [comment]
Ha thanks but the majority of income is (designed to be) from sales of Motion+ and corporate sponsorships, I only have that page open as some sponsors have explained they can only do through GitHub.
