### ISSUE TITLE
[BUG] Missing License for motion-dom

### ISSUE THREAD

**Issue by janeisenmenger** [motiondivision/motion#2938]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

With 11.13.5, the new package motion-dom is used. It does not have a license attached. This is causing our license checker to fail, as we require a license to be available.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

n/a - see steps to reproduce.

**4. Steps to reproduce**

Go to https://registry.npmjs.org/motion-dom for the metadata for motion-dom

**5. Expected behavior**

A license field is set to "MIT" 

Actual behaviour: There is no 'license' field. Compare it to https://registry.npmjs.org/framer-motion, where the field 'license' is set to MIT.

**6. Video or screenshots**

n/a

**7. Environment details**

n/a

**Comment by mattgperry** [comment]
Thanks for the PR, fix going out in 11.14.1
