### ISSUE TITLE
[BUG] NexusIQ is not able to detects license for motion-utils and motion-dom

### ISSUE THREAD

**Issue by Hagendorn** [motiondivision/motion#2939]
We are using NexusIQ to detect license problems with installed packages and NexusIQ reports some issues with motion-utils and motion-dom, because there is no license definition in the package.json. This has also the effect, that npm displays it as "License: none"

![Bildschirmfoto 2024-12-12 um 12 55 24](https://github.com/user-attachments/assets/39fcdfd8-a796-4b44-be68-db53fb26bd5f)
![Bildschirmfoto 2024-12-12 um 12 55 46](https://github.com/user-attachments/assets/a99a41be-dc2d-4167-a461-45a9d2965dd9)

The package itself contains a `LICENSE.md` file with an MIT license. Please add this information also in the `package.json`

**Comment by Hagendorn** [comment]
I will create a PR for it.

**Comment by Hagendorn** [comment]
@janeisenmenger funny, we must have overlapped in time 😄 when creating the bug report. I have also seen that my PR is no longer necessary, as it has already been fixed in the meantime. i am closing my bug

**Comment by mattgperry** [comment]
Glad it's fixed!
